language: ruby
sudo: false
cache: bundler
script: 'script/ci'
before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.13.7
rvm:
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.1.6.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fde2367248d53de4fe70
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always
